# Generated by Django 4.2.11 on 2024-05-15 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="price",
            new_name="close_price",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="name",
        ),
        migrations.AddField(
            model_name="stock",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="stock",
            name="high_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock",
            name="low_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock",
            name="open_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stock",
            name="volume",
            field=models.BigIntegerField(),
        ),
    ]
